
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"img\amenities_img") #Kevin Note: ur path to where the frame0 file is


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()

window.geometry("1920x1080")
window.configure(bg = "#FFFFFF")


canvas = Canvas(
    window,
    bg = "#FFFFFF",
    height = 1080,
    width = 1920,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
canvas.create_rectangle(
    0.0,
    0.0,
    1920.0,
    1080.0,
    fill="#D9D9D9",
    outline="")

image_image_1 = PhotoImage(
    file=relative_to_assets("image_1.png"))
image_1 = canvas.create_image(
    960.0,
    613.0,
    image=image_image_1
)

canvas.create_rectangle(
    0.0,
    0.0,
    1920.0,
    180.0,
    fill="#006196",
    outline="")

button_image_1 = PhotoImage(
    file=relative_to_assets("button_1.png"))
button_1 = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_1 clicked"),
    relief="flat"
)
button_1.place(
    x=1417.0,
    y=94.0,
    width=214.0751953125,
    height=79.0
)

canvas.create_rectangle(
    1634.0,
    94.0,
    1920.0,
    173.0,
    fill="#002337",
    outline="")

button_image_2 = PhotoImage(
    file=relative_to_assets("button_2.png"))
button_2 = Button(
    image=button_image_2,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_2 clicked"),
    relief="flat"
)
button_2.place(
    x=0.0,
    y=94.0,
    width=330.0,
    height=79.0
)

button_image_3 = PhotoImage(
    file=relative_to_assets("button_3.png"))
button_3 = Button(
    image=button_image_3,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_3 clicked"),
    relief="flat"
)
button_3.place(
    x=1200.0,
    y=94.0,
    width=214.0751953125,
    height=79.0
)

button_image_4 = PhotoImage(
    file=relative_to_assets("button_4.png"))
button_4 = Button(
    image=button_image_4,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_4 clicked"),
    relief="flat"
)
button_4.place(
    x=983.0,
    y=94.0,
    width=214.0751953125,
    height=79.0
)

button_image_5 = PhotoImage(
    file=relative_to_assets("button_5.png"))
button_5 = Button(
    image=button_image_5,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_5 clicked"),
    relief="flat"
)
button_5.place(
    x=767.0,
    y=94.0,
    width=214.07513427734375,
    height=79.0
)

button_image_6 = PhotoImage(
    file=relative_to_assets("button_6.png"))
button_6 = Button(
    image=button_image_6,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_6 clicked"),
    relief="flat"
)
button_6.place(
    x=550.0,
    y=94.0,
    width=214.07513427734375,
    height=79.0
)

button_image_7 = PhotoImage(
    file=relative_to_assets("button_7.png"))
button_7 = Button(
    image=button_image_7,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_7 clicked"),
    relief="flat"
)
button_7.place(
    x=333.0,
    y=94.0,
    width=214.07513427734375,
    height=79.0
)

image_image_2 = PhotoImage(
    file=relative_to_assets("image_2.png"))
image_2 = canvas.create_image(
    62.0,
    46.0,
    image=image_image_2
)

button_image_8 = PhotoImage(
    file=relative_to_assets("button_8.png"))
button_8 = Button(
    image=button_image_8,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_8 clicked"),
    relief="flat"
)
button_8.place(
    x=1663.0,
    y=108.0,
    width=54.0,
    height=54.0
)

button_image_9 = PhotoImage(
    file=relative_to_assets("button_9.png"))
button_9 = Button(
    image=button_image_9,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_9 clicked"),
    relief="flat"
)
button_9.place(
    x=1752.0,
    y=108.0,
    width=54.0,
    height=54.0
)

button_image_10 = PhotoImage(
    file=relative_to_assets("button_10.png"))
button_10 = Button(
    image=button_image_10,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_10 clicked"),
    relief="flat"
)
button_10.place(
    x=1837.0,
    y=108.0,
    width=54.0,
    height=54.0
)

image_image_3 = PhotoImage(
    file=relative_to_assets("image_3.png"))
image_3 = canvas.create_image(
    1193.0,
    421.0,
    image=image_image_3
)

image_image_4 = PhotoImage(
    file=relative_to_assets("image_4.png"))
image_4 = canvas.create_image(
    1193.0,
    819.0,
    image=image_image_4
)

image_image_5 = PhotoImage(
    file=relative_to_assets("image_5.png"))
image_5 = canvas.create_image(
    426.0,
    819.0,
    image=image_image_5
)

image_image_6 = PhotoImage(
    file=relative_to_assets("image_6.png"))
image_6 = canvas.create_image(
    426.0,
    421.0,
    image=image_image_6
)

canvas.create_text(
    643.0,
    291.0,
    anchor="nw",
    text="Located between Rinks B and C in the main lobby.\n\nFood Provided for all day\nBreakfast, Lunch, and Dinner\nGreat for skating snacks too! \nHours: Mon - Fri : 11am - 7pm",
    fill="#000000",
    font=("Inter Regular", 16 * -1)
)

canvas.create_text(
    643.0,
    689.0,
    anchor="nw",
    text="\nLocated in the Detroit Skating Club.\n\nindependent service\nspecializing in figure skate\nsharpening, blade mounting\nand analysis of skate-related\nproblems.\n\nProfessional level skill set.\nworked with many athletes\nOlympic, World and More.",
    fill="#000000",
    font=("Inter Regular", 16 * -1)
)

canvas.create_text(
    1411.0,
    292.0,
    anchor="nw",
    text="\nHeld in the spring and the fall.\n\nGreat way to clean out your closets of old figure skating stuff.\n\nItems must be washed and on\nhangers, as well as, priced and\ntagged using the sale tags and\ninventory forms below.\nExample items:\nSkates, Jackets, leggings, bags\n\nContact Andrea in Main office for info",
    fill="#000000",
    font=("Inter Regular", 14 * -1)
)

canvas.create_text(
    1411.0,
    688.0,
    anchor="nw",
    text="\nLocated between Rinks A and B.\n\nOffering Skate Apparel, Skate\nPurchase, Skate Rental and More.\n\nDetroit Custom Skate Shop (DCS) is\nDCS offers long-term skate rentals \nas well as 1 day rentals.\nPhone: 248-335-8790\nMon-Thurs: 10:00am – 7:00pm\nFri: 10:00am – 6:00pm\nSat: 9:00am – 4:00pm\nSun: Call for Hours",
    fill="#000000",
    font=("Inter Regular", 14 * -1)
)

canvas.create_rectangle(
    226.0,
    241.0,
    888.0,
    291.0,
    fill="#006196",
    outline="")

canvas.create_text(
    226.0,
    241.0,
    anchor="nw",
    text="Ice Sports Cafe",
    fill="#FFFFFF",
    font=("Inter ExtraBold", 28 * -1)
)

canvas.create_rectangle(
    226.0,
    639.0,
    888.0,
    689.0,
    fill="#006196",
    outline="")

canvas.create_text(
    226.0,
    639.0,
    anchor="nw",
    text="Fred’s Skate Sharpening",
    fill="#FFFFFF",
    font=("Inter ExtraBold", 28 * -1)
)

canvas.create_rectangle(
    993.0,
    241.0,
    1655.0,
    291.0,
    fill="#006196",
    outline="")

canvas.create_text(
    993.0,
    241.0,
    anchor="nw",
    text="Used Skates and Apparel",
    fill="#FFFFFF",
    font=("Inter ExtraBold", 28 * -1)
)

canvas.create_rectangle(
    993.0,
    639.0,
    1655.0,
    689.0,
    fill="#006196",
    outline="")

canvas.create_text(
    993.0,
    639.0,
    anchor="nw",
    text="Detroit Custom Skate Shop",
    fill="#FFFFFF",
    font=("Inter ExtraBold", 28 * -1)
)

button_image_11 = PhotoImage(
    file=relative_to_assets("button_11.png"))
button_11 = Button(
    image=button_image_11,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_11 clicked"),
    relief="flat"
)
button_11.place(
    x=226.0,
    y=968.0,
    width=400.0,
    height=50.0
)

button_image_12 = PhotoImage(
    file=relative_to_assets("button_12.png"))
button_12 = Button(
    image=button_image_12,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_12 clicked"),
    relief="flat"
)
button_12.place(
    x=993.0,
    y=968.0,
    width=400.0,
    height=50.0
)

button_image_13 = PhotoImage(
    file=relative_to_assets("button_13.png"))
button_13 = Button(
    image=button_image_13,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_13 clicked"),
    relief="flat"
)
button_13.place(
    x=993.0,
    y=564.0,
    width=192.0,
    height=50.0
)

button_image_14 = PhotoImage(
    file=relative_to_assets("button_14.png"))
button_14 = Button(
    image=button_image_14,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_14 clicked"),
    relief="flat"
)
button_14.place(
    x=1201.0,
    y=564.0,
    width=192.0,
    height=50.0
)
window.resizable(False, False)
window.mainloop()
